import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import React from "react";
import { Header } from "../components";
import { Footer } from "../components/Footer/Footer";

export const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "900", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} bg-darkBlue-950 text-white relative w-full`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
